### ISSUE TITLE
thriftrw should handle bad thrift req format gracefully

### ISSUE THREAD

**Issue by ShanniLi** [uber/thriftrw#54]
cc: @kriskowal @Raynos @jcorbin  
Refer to https://github.com/uber/tchannel/pull/1188

 - test sending a request with a malformed thrift IDL where we send an empty body. Assert BadRequest
   Actual response:
  /Users/juncaoli/workspace/tchannel/src2/node/hyperbahn/handler.js:390
    var serviceName = body.query.serviceName;
                                ^
TypeError: Cannot read property 'serviceName' of null
    at discover (/Users/juncaoli/workspace/tchannel/src2/node/hyperbahn/handler.js:390:33)
    at HyperbahnHandler.handleThriftRequest (/Users/juncaoli/workspace/tchannel/src2/node/as/thrift.js:165:9)
    at RequestCallbackHandler.handleRequest (/Users/juncaoli/workspace/tchannel/src2/node/request-handler.js:62:23)
    at HyperbahnHandler.handleRequest (/Users/juncaoli/workspace/tchannel/src2/node/endpoint-handler.js:71:17)
    at ServiceDispatchHandler.handleRequest (/Users/juncaoli/workspace/tchannel/src2/node/hyperbahn/service_proxy.js:121:22)
    at TChannelConnection.runHandler (/Users/juncaoli/workspace/tchannel/src2/node/connection_base.js:134:26)
    at runHandler (/Users/juncaoli/workspace/tchannel/src2/node/connection_base.js:116:14)
    at process._tickCallback (node.js:419:13)

 - test sending a request with a malformed thrift IDL where we send a body with a query without the serviceName field. Assert BadRequest
   Actually response is the same as above.

 - test sending a request with a malformed thrift IDL which has zero exceptions defined; Send a request with empty string serviceName. Assert that the client doesn't blow up and gets back a not ok response. 
  Actually response: 
assert.js:92
  throw new assert.AssertionError({
  ^
AssertionError: expected not-ok response to have typeName
    at handleThriftResponse (/Users/juncaoli/workspace/tchannel/src2/node/as/thrift.js:9:8146)
    at onResponse (/Users/juncaoli/workspace/tchannel/src2/node/hyperbahn/handler.js:9:18233)
    at handleResponse (/Users/juncaoli/workspace/tchannel/src2/node/as/thrift.js:9:11266)
    at DefinedEvent.onResponse [as listener] (/Users/juncaoli/workspace/tchannel/src2/node/out_request.js:9:22423)
    at DefinedEvent.emit (/Users/juncaoli/workspace/tchannel/src2/node/lib/event_emitter.js:9:3685)
    at V2OutRequest.emitResponse (/Users/juncaoli/workspace/tchannel/src2/node/out_request.js:9:13637)
    at TChannelConnection.onCallResponse (/Users/juncaoli/workspace/tchannel/src2/node/connection.js:9:12385)
    at DefinedEvent.onCallResponse [as listener] (/Users/juncaoli/workspace/tchannel/src2/node/connection.js:9:7490)
    at DefinedEvent.emit (/Users/juncaoli/workspace/tchannel/src2/node/lib/event_emitter.js:9:3685)
✓ get no hostelV2Handler.handleCallResponse (/Users/juncaoli/workspace/tchannel/src2/node/v2/handler.js:9:20587)

**Comment by ShanniLi** [comment]
FYI. The tests revealing these issues are present but commented out in the referenced PR.

**Comment by kriskowal** [comment]
Fixed in #56
