### ISSUE TITLE
Function with void return causes parser error.

### ISSUE THREAD

**Issue by Willyham** [uber/thriftrw#58]
@kriskowal 

```
AssertionError: "Can't get reader/writer for definition with unknown type undefined" undefined "undefined"
    at Thrift.resolve (/home/willy/Projects/troy/thriftrw/thrift.js:239:16)
    at ThriftField.link (/home/willy/Projects/troy/thriftrw/struct.js:59:27)
    at ThriftStruct.link (/home/willy/Projects/troy/thriftrw/struct.js:184:28)
    at Thrift.link (/home/willy/Projects/troy/thriftrw/thrift.js:200:32)
    at new Thrift (/home/willy/Projects/troy/thriftrw/thrift.js:69:10)
    at Object.<anonymous> (/home/willy/Projects/troy/thriftrw/test/void.js:51:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by Willyham** [comment]
```
service Foo {
    void foo(
        1: required string foo;
    )
}
```

To recreate.

**Comment by AudLaw** [comment]
Seeing the same assert with functions with returns: uber@audrey:~/gocode/src/code.uber.internal/safety/mutombo$  tcurl -p localhost:10000 -t ./thrift/ mutombo Mutombo::NeedVerification -3 '{"params": {"driverUuid":"f6be040f-d3bb-424c-ba74-50cc7fc24000","cityId":"1"}}'

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "Can't get reader/writer for definition with unknown type undefined" undefined "undefined"
    at Thrift.resolve (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:237:16)
    at ThriftField.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:59:27)
    at ThriftStruct.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:184:28)
    at Thrift.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:199:32)
    at new Thrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:69:10)
    at new TChannelAsThrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/as/thrift.js:46:17)
    at asThrift (/usr/lib/node_modules/tcurl/index.js:324:18)
    at onIdentified (/usr/lib/node_modules/tcurl/index.js:278:13)
    at finish (/usr/lib/node_modules/tcurl/node_modules/tchannel/peer.js:266:9)
    at Array.onIdentified [as 1] (/usr/lib/node_modules/tcurl/node_modules/tchannel/peer.js:257:9)

for 
struct NeedVerificationParams {
  1: required string driverUuid
  2: optional string cityId
}

service Mutombo {
  bool NeedVerification(
    1: required NeedVerificationParams params
  ) throws(
    1: InternalServerError internalServerError
    2: IllegalParamError illegalParamError
  )

After switching back to tcurl 4.12.1 I'm no longer seeing the problem.

**Comment by AudLaw** [comment]
I'm also seeing with a non-void return case:
struct Params {
  1: required string uuid
  2: optional string id
}

service M {
  bool N(
    1: required Params params
  ) 

AssertionError: "Can't get reader/writer for definition with unknown type undefined" undefined "undefined"
    at Thrift.resolve (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:237:16)
    at ThriftField.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:59:27)
    at ThriftStruct.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:184:28)
    at Thrift.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:199:32)
    at new Thrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:69:10)
    at new TChannelAsThrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/as/thrift.js:46:17)
    at asThrift (/usr/lib/node_modules/tcurl/index.js:324:18)
    at onIdentified (/usr/lib/node_modules/tcurl/index.js:278:13)
    at finish (/usr/lib/node_modules/tcurl/node_modules/tchannel/peer.js:266:9)
    at Array.onIdentified [as 1] (/usr/lib/node_modules/tcurl/node_modules/tchannel/peer.js:257:9)

Not seeing the problem after switching back to tcurl 4.12.1 from 4.12.2

**Comment by kriskowal** [comment]
Thanks for the find and isolated case. See #59
